Add missing Wayland header after cb75c422e529
vulkancapsviewer.cpp:765:41: error: use of undeclared identifier 'wl_display_connect'
            surfaceCreateInfo.display = wl_display_connect(NULL);
                                        ^